/* pvz_state.h: pvz-rl shared state, schema v1 (step 1.1).
 * GENERATED by `python -m schema.gen --write` from pvz-rl schema/spec.py. Do not edit.
 * The emulator fork carries a byte-identical copy of pvz_state.h at schema/pvz_state.h.
 *
 * The contract between the emulator adapter (x64, MSVC), the real-game harness (i686,
 * LLVM-MinGW) and the Python agent (NumPy dtype schema.PVZ_STATE_DTYPE).
 *
 * Layout rules
 * - Only int32_t, uint32_t, float (32-bit) and uint8_t[n] with n a multiple of 4. Enums
 *   stored as int32_t. Alignment 4 everywhere; no #pragma pack; explicit _pad fields
 *   written as zero. Little-endian.
 * - Every offset and sizeof is asserted below.
 * - Arrays: count + fixed capacity; entries [0,count) live, ascending slot order; bytes
 *   in [count,cap) unspecified, never read, not zeroed; overflow = number of live
 *   entries that did not fit (first cap written, count = cap).
 * - Units: ticks at 100/s; pixels float32 in each world's own frame (plant int -> float
 *   exact); row/col 0-based, row 0 top. Producers pass pixel values through unchanged.
 * - Codes: plant/zombie/grid-item/accessory TYPE codes = the emulator enum values. STATUS
 *   codes are carried raw (status_raw, world-specific) and encoder v1 must not read them.
 * - valid bitmask: a producer sets a group's bit only if it filled every field in the
 *   group; the harness only if every address it read is VERIFIED.
 * - Any layout change bumps PVZ_STATE_VERSION; the bridge handshake checks magic,
 *   version, layout hash and size.
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
#define PVZ_STATIC_ASSERT(cond, msg) static_assert(cond, msg)
#else
#define PVZ_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
#endif

/* ---- version, size, handshake ---- */
#define PVZ_STATE_VERSION     1
#define PVZ_STATE_SIZE        59848       /* bytes */
#define PVZ_STATE_LAYOUT_HASH 0x428a9a89u /* first 4 bytes of the spec sha256 */
#define PVZ_STATE_MAGIC       1398429264u /* ASCII "PVZS" as a little-endian uint32 (design constant) */

/* ---- array capacities (design choices) ---- */
#define PVZ_MAX_CARDS     10
#define PVZ_MAX_PLANTS    256
#define PVZ_MAX_ZOMBIES   512
#define PVZ_MAX_GRIDITEMS 128
#define PVZ_MAX_MOWERS    8

/* ---- world codes ---- */
#define PVZ_WORLD_EMULATOR 1
#define PVZ_WORLD_GAME     2

/* ---- phase codes ---- */
#define PVZ_PHASE_UNKNOWN     0
#define PVZ_PHASE_PLAYING     1
#define PVZ_PHASE_CARD_SELECT 2
#define PVZ_PHASE_GAME_OVER   3
#define PVZ_PHASE_OTHER       4

/* ---- cob_state codes ---- */
#define PVZ_COB_STATE_NOT_COB  0           /* not a cob */
#define PVZ_COB_STATE_UNARMED  1
#define PVZ_COB_STATE_CHARGING 2
#define PVZ_COB_STATE_ARMED    3
#define PVZ_COB_STATE_FIRING   4

/* ---- mower_state codes ---- */
#define PVZ_MOWER_STATE_READY  1
#define PVZ_MOWER_STATE_MOVING 2

/* ---- card_type codes ---- */
#define PVZ_CARD_TYPE_EMPTY (-1)        /* cards[].type of an empty slot */

/* ---- valid bits: index (BIT_) and mask ---- */
#define PVZ_VALID_BIT_CORE             0
#define PVZ_VALID_CORE                 1u          /* tick, sun, scene, paused */
#define PVZ_VALID_BIT_PHASE            1
#define PVZ_VALID_PHASE                2u          /* phase */
#define PVZ_VALID_BIT_GAME_OVER        2
#define PVZ_VALID_GAME_OVER            4u
#define PVZ_VALID_BIT_WAVE             3
#define PVZ_VALID_WAVE                 8u          /* wave, next_wave_countdown, next_wave_is_huge */
#define PVZ_VALID_BIT_FLAG             4
#define PVZ_VALID_FLAG                 16u         /* flag */
#define PVZ_VALID_BIT_ROUND_TYPES      5
#define PVZ_VALID_ROUND_TYPES          32u         /* round_zombie_types */
#define PVZ_VALID_BIT_CARDS            6
#define PVZ_VALID_CARDS                64u         /* cards[] */
#define PVZ_VALID_BIT_PLANT_BASIC      7
#define PVZ_VALID_PLANT_BASIC          128u        /* id, type, row, col */
#define PVZ_VALID_BIT_PLANT_POS        8
#define PVZ_VALID_PLANT_POS            256u        /* x, y */
#define PVZ_VALID_BIT_PLANT_HP         9
#define PVZ_VALID_PLANT_HP             512u        /* hp, max_hp */
#define PVZ_VALID_BIT_PLANT_STATUS     10
#define PVZ_VALID_PLANT_STATUS         1024u       /* status_raw, flags */
#define PVZ_VALID_BIT_PLANT_COUNTDOWNS 11
#define PVZ_VALID_PLANT_COUNTDOWNS     2048u       /* state_countdown, shoot_countdown, effect_countdown */
#define PVZ_VALID_BIT_COB_STATE        12
#define PVZ_VALID_COB_STATE            4096u       /* cob_state, cob_recharge_countdown */
#define PVZ_VALID_BIT_COB_CHARGE       13
#define PVZ_VALID_COB_CHARGE           8192u       /* cob_charge_progress */
#define PVZ_VALID_BIT_Z_BASIC          14
#define PVZ_VALID_Z_BASIC              16384u      /* id, type, row, x, y */
#define PVZ_VALID_BIT_Z_HP             15
#define PVZ_VALID_Z_HP                 32768u      /* hp */
#define PVZ_VALID_BIT_Z_MAX_HP         16
#define PVZ_VALID_Z_MAX_HP             65536u      /* max_hp */
#define PVZ_VALID_BIT_ACC_HP           17
#define PVZ_VALID_ACC_HP               131072u     /* acc1_hp, acc2_hp */
#define PVZ_VALID_BIT_ACC_TYPE         18
#define PVZ_VALID_ACC_TYPE             262144u     /* types and max hp */
#define PVZ_VALID_BIT_Z_STATUS         19
#define PVZ_VALID_Z_STATUS             524288u     /* status_raw, DYING */
#define PVZ_VALID_BIT_Z_EATING         20
#define PVZ_VALID_Z_EATING             1048576u    /* EATING */
#define PVZ_VALID_BIT_Z_IN_WATER       21
#define PVZ_VALID_Z_IN_WATER           2097152u    /* IN_WATER */
#define PVZ_VALID_BIT_Z_FLYING         22
#define PVZ_VALID_Z_FLYING             4194304u    /* FLYING */
#define PVZ_VALID_BIT_Z_HYPNO          23
#define PVZ_VALID_Z_HYPNO              8388608u    /* HYPNO */
#define PVZ_VALID_BIT_Z_DEBUFF         24
#define PVZ_VALID_Z_DEBUFF             16777216u   /* slow, freeze, butter */
#define PVZ_VALID_BIT_Z_SPAWN_WAVE     25
#define PVZ_VALID_Z_SPAWN_WAVE         33554432u   /* spawn_wave */
#define PVZ_VALID_BIT_GRID             26
#define PVZ_VALID_GRID                 67108864u   /* type, row, col */
#define PVZ_VALID_BIT_GRID_COUNTDOWN   27
#define PVZ_VALID_GRID_COUNTDOWN       134217728u  /* countdown_raw */
#define PVZ_VALID_BIT_MOWERS           28
#define PVZ_VALID_MOWERS               268435456u  /* mowers[] */

/* ---- plant_flag bits: index (BIT_) and mask ---- */
#define PVZ_PLANT_FLAG_BIT_SLEEPING 0
#define PVZ_PLANT_FLAG_SLEEPING     1u
#define PVZ_PLANT_FLAG_BIT_SMASHED  1
#define PVZ_PLANT_FLAG_SMASHED      2u

/* ---- zombie_flag bits: index (BIT_) and mask ---- */
#define PVZ_ZOMBIE_FLAG_BIT_EATING   0
#define PVZ_ZOMBIE_FLAG_EATING       1u
#define PVZ_ZOMBIE_FLAG_BIT_IN_WATER 1
#define PVZ_ZOMBIE_FLAG_IN_WATER     2u
#define PVZ_ZOMBIE_FLAG_BIT_FLYING   2
#define PVZ_ZOMBIE_FLAG_FLYING       4u          /* balloon airborne only; emulator object/zombie.h:231-234 */
#define PVZ_ZOMBIE_FLAG_BIT_DYING    3
#define PVZ_ZOMBIE_FLAG_DYING        8u          /* emulator object/zombie.h:240-244; game state 1/2/3 */
#define PVZ_ZOMBIE_FLAG_BIT_HYPNO    4
#define PVZ_ZOMBIE_FLAG_HYPNO        16u

/* ---- pvz_header_t ---- */
/* Header, 128 bytes. */
typedef struct pvz_header_t {
    /* @0 magic: uint32_t.
     * PVZ_STATE_MAGIC (design constant) */
    uint32_t magic;
    /* @4 schema_version: uint32_t.
     * = PVZ_STATE_VERSION */
    uint32_t schema_version;
    /* @8 layout_hash: uint32_t.
     * first 4 bytes of the spec sha256 (= PVZ_STATE_LAYOUT_HASH) */
    uint32_t layout_hash;
    /* @12 struct_size: uint32_t, bytes.
     * = PVZ_STATE_SIZE */
    uint32_t struct_size;
    /* @16 world: uint32_t.
     * PVZ_WORLD_*: 1 emulator, 2 game; logs only */
    uint32_t world;
    /* @20 valid: uint32_t.
     * PVZ_VALID_* bitmask: a producer sets a group's bit only if it filled every field in
     *   the group; the harness only if every address it read is VERIFIED */
    uint32_t valid;
    /* @24 tick: uint32_t, ticks at 100/s. valid: PVZ_VALID_CORE.
     * +1 per simulated update in play; frozen while paused/card select. The encoder never
     *   uses the absolute value.
     * emulator: scene.tick: +1 per simulated update, frozen after game over, 0 after a
     *   reset (emulator world.cpp:28-29, object/scene.cpp:275)
     * game: board.game_clock */
    uint32_t tick;
    /* @28 phase: int32_t. valid: PVZ_VALID_PHASE.
     * PVZ_PHASE_*: 0 unknown, 1 playing, 2 card select, 3 game over, 4 other
     * emulator: is_game_over->3 else 1; never reports card select (the env calls
     *   select_plants at round boundaries)
     * game: game_ui 2/3, game over unk */
    int32_t phase;
    /* @32 paused: int32_t. valid: PVZ_VALID_CORE.
     * emulator: 0
     * game: board.game_paused */
    int32_t paused;
    /* @36 scene: int32_t. valid: PVZ_VALID_CORE.
     * raw scene code; pool = 2 in both */
    int32_t scene;
    /* @40 flag: int32_t. valid: PVZ_VALID_FLAG.
     * 2 x rounds completed + (1 if wave >= 10)
     * emulator: total_flags follows this rule exactly (+1 when wave reaches 10, +1 at round
     *   end); written as total_flags minus its start value (emulator object/scene.h:91,
     *   object/scene.cpp:288), so the field is 0-based in both worlds
     * game: 2 x completed_rounds + (wave >= 10) */
    int32_t flag;
    /* @44 wave: int32_t. valid: PVZ_VALID_WAVE.
     * waves spawned this round, 0..20
     * emulator: spawn.wave
     * game: board.wave, meaning to confirm in 3.3 */
    int32_t wave;
    /* @48 next_wave_countdown: int32_t, ticks. valid: PVZ_VALID_WAVE.
     * emulator: countdown.next_wave
     * game: refresh_countdown, unk */
    int32_t next_wave_countdown;
    /* @52 next_wave_is_huge: int32_t. valid: PVZ_VALID_WAVE.
     * wave % 10 == 9, derived in both (AvZ time_queue.cpp:13 and the emulator banner at
     *   waves 9/19 agree) */
    int32_t next_wave_is_huge;
    /* @56 sun: int32_t. valid: PVZ_VALID_CORE. */
    int32_t sun;
    /* @60 n_plants: int32_t. valid: PVZ_VALID_PLANT_BASIC.
     * live entries in plants[] */
    int32_t n_plants;
    /* @64 plants_overflow: int32_t. valid: PVZ_VALID_PLANT_BASIC.
     * live plants that did not fit */
    int32_t plants_overflow;
    /* @68 n_zombies: int32_t. valid: PVZ_VALID_Z_BASIC.
     * live entries in zombies[] */
    int32_t n_zombies;
    /* @72 zombies_overflow: int32_t. valid: PVZ_VALID_Z_BASIC.
     * live zombies that did not fit */
    int32_t zombies_overflow;
    /* @76 n_griditems: int32_t. valid: PVZ_VALID_GRID.
     * live entries in griditems[] */
    int32_t n_griditems;
    /* @80 griditems_overflow: int32_t. valid: PVZ_VALID_GRID.
     * live grid items that did not fit */
    int32_t griditems_overflow;
    /* @84 n_mowers: int32_t. valid: PVZ_VALID_MOWERS.
     * live entries in mowers[] */
    int32_t n_mowers;
    /* @88 mowers_overflow: int32_t. valid: PVZ_VALID_MOWERS.
     * live mowers that did not fit */
    int32_t mowers_overflow;
    /* @92 round_zombie_types: uint8_t[36]. valid: PVZ_VALID_ROUND_TYPES.
     * multi-hot by zombie type code; 33 used
     * emulator: spawn_flags[33]
     * game: zombie_type_list 33 one-byte bools */
    uint8_t round_zombie_types[36];
} pvz_header_t;

PVZ_STATIC_ASSERT(sizeof(pvz_header_t) == 128, "pvz_header_t size");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, magic) == 0, "pvz_header_t.magic");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, schema_version) == 4, "pvz_header_t.schema_version");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, layout_hash) == 8, "pvz_header_t.layout_hash");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, struct_size) == 12, "pvz_header_t.struct_size");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, world) == 16, "pvz_header_t.world");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, valid) == 20, "pvz_header_t.valid");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, tick) == 24, "pvz_header_t.tick");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, phase) == 28, "pvz_header_t.phase");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, paused) == 32, "pvz_header_t.paused");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, scene) == 36, "pvz_header_t.scene");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, flag) == 40, "pvz_header_t.flag");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, wave) == 44, "pvz_header_t.wave");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, next_wave_countdown) == 48, "pvz_header_t.next_wave_countdown");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, next_wave_is_huge) == 52, "pvz_header_t.next_wave_is_huge");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, sun) == 56, "pvz_header_t.sun");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, n_plants) == 60, "pvz_header_t.n_plants");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, plants_overflow) == 64, "pvz_header_t.plants_overflow");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, n_zombies) == 68, "pvz_header_t.n_zombies");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, zombies_overflow) == 72, "pvz_header_t.zombies_overflow");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, n_griditems) == 76, "pvz_header_t.n_griditems");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, griditems_overflow) == 80, "pvz_header_t.griditems_overflow");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, n_mowers) == 84, "pvz_header_t.n_mowers");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, mowers_overflow) == 88, "pvz_header_t.mowers_overflow");
PVZ_STATIC_ASSERT(offsetof(pvz_header_t, round_zombie_types) == 92, "pvz_header_t.round_zombie_types");

/* ---- pvz_card_t ---- */
/* Card, 20 bytes. */
typedef struct pvz_card_t {
    /* @0 type: int32_t. valid: PVZ_VALID_CARDS.
     * plant type code = the emulator enum value; -1 empty (PVZ_CARD_TYPE_EMPTY) */
    int32_t type;
    /* @4 imitater_type: int32_t. valid: PVZ_VALID_CARDS.
     * plant type code = the emulator enum value */
    int32_t imitater_type;
    /* @8 cd_remaining: int32_t, ticks. valid: PVZ_VALID_CARDS.
     * 0 = ready
     * emulator: cold_down
     * game: initial_cd - cd + 1 per avz_card.cpp:259 */
    int32_t cd_remaining;
    /* @12 cd_total: int32_t, ticks. valid: PVZ_VALID_CARDS.
     * the cooldown table entry of the card's type, or of the imitater's target for an
     *   imitater card; 0 for an empty card
     * emulator: CD_TABLE[target], target = the imitater's type for an imitater card
     *   (emulator system/plant/plant_factory.cpp:464, :541; object/plant.cpp:38-45)
     * game: seed.initial_cd */
    int32_t cd_total;
    /* @16 usable: int32_t. valid: PVZ_VALID_CARDS.
     * type is not empty and cd_remaining == 0; sun not considered */
    int32_t usable;
} pvz_card_t;

PVZ_STATIC_ASSERT(sizeof(pvz_card_t) == 20, "pvz_card_t size");
PVZ_STATIC_ASSERT(offsetof(pvz_card_t, type) == 0, "pvz_card_t.type");
PVZ_STATIC_ASSERT(offsetof(pvz_card_t, imitater_type) == 4, "pvz_card_t.imitater_type");
PVZ_STATIC_ASSERT(offsetof(pvz_card_t, cd_remaining) == 8, "pvz_card_t.cd_remaining");
PVZ_STATIC_ASSERT(offsetof(pvz_card_t, cd_total) == 12, "pvz_card_t.cd_total");
PVZ_STATIC_ASSERT(offsetof(pvz_card_t, usable) == 16, "pvz_card_t.usable");

/* ---- pvz_plant_t ---- */
/* Plant, 64 bytes. Written iff live and not dead: emulator !is_dead; game !is_disappeared.
 * Pumpkin, lily pad, coffee bean are separate entries in the same cell. The three countdown
 * pairings are hypotheses for 3.10/4.4. */
typedef struct pvz_plant_t {
    /* @0 id: int32_t. valid: PVZ_VALID_PLANT_BASIC.
     * slot/array index */
    int32_t id;
    /* @4 type: int32_t. valid: PVZ_VALID_PLANT_BASIC.
     * plant type code = the emulator enum value */
    int32_t type;
    /* @8 row: int32_t. valid: PVZ_VALID_PLANT_BASIC.
     * 0-based, row 0 top */
    int32_t row;
    /* @12 col: int32_t. valid: PVZ_VALID_PLANT_BASIC.
     * 0-based; a cob's LEFT cell */
    int32_t col;
    /* @16 status_raw: int32_t. valid: PVZ_VALID_PLANT_STATUS.
     * raw status code, world-specific; encoder v1 must not read it */
    int32_t status_raw;
    /* @20 x: float, px, float32 in this world's own frame. valid: PVZ_VALID_PLANT_POS. */
    float x;
    /* @24 y: float, px, float32 in this world's own frame. valid: PVZ_VALID_PLANT_POS. */
    float y;
    /* @28 hp: int32_t. valid: PVZ_VALID_PLANT_HP. */
    int32_t hp;
    /* @32 max_hp: int32_t. valid: PVZ_VALID_PLANT_HP. */
    int32_t max_hp;
    /* @36 state_countdown: int32_t, ticks. valid: PVZ_VALID_PLANT_COUNTDOWNS.
     * emulator: countdown.status
     * game: plant.state_countdown, unk */
    int32_t state_countdown;
    /* @40 shoot_countdown: int32_t, ticks. valid: PVZ_VALID_PLANT_COUNTDOWNS.
     * emulator: countdown.generate
     * game: shoot_countdown, unk */
    int32_t shoot_countdown;
    /* @44 effect_countdown: int32_t, ticks. valid: PVZ_VALID_PLANT_COUNTDOWNS.
     * emulator: countdown.effect
     * game: explode_countdown, unk */
    int32_t effect_countdown;
    /* @48 cob_state: int32_t. valid: PVZ_VALID_COB_STATE.
     * PVZ_COB_STATE_*: 0 not a cob, 1 unarmed, 2 charging, 3 armed, 4 firing
     * emulator: 0x23->1, 0x24->2, 0x26->3, 0x25->4
     * game: 35->1, 36->2, 37->3, 38->4 per AvZ, unk for 1096 */
    int32_t cob_state;
    /* @52 cob_recharge_countdown: int32_t, ticks. valid: PVZ_VALID_COB_STATE.
     * the unarmed countdown while the cob is unarmed, else 0
     * emulator: countdown.status while unarmed (emulator system/plant/cob_cannon.cpp:9-13)
     * game: state_countdown, unk */
    int32_t cob_recharge_countdown;
    /* @56 cob_charge_progress: float. valid: PVZ_VALID_COB_CHARGE.
     * 0..1 progress of the charge animation while charging, else 0
     * emulator: reanim.progress (emulator system/reanim.cpp:163-178,
     *   system/plant/cob_cannon.cpp:11-19)
     * game: animation.circulation_rate, unk */
    float cob_charge_progress;
    /* @60 flags: uint32_t. valid: PVZ_VALID_PLANT_STATUS.
     * PVZ_PLANT_FLAG_*: bit0 SLEEPING, bit1 SMASHED */
    uint32_t flags;
} pvz_plant_t;

PVZ_STATIC_ASSERT(sizeof(pvz_plant_t) == 64, "pvz_plant_t size");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, id) == 0, "pvz_plant_t.id");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, type) == 4, "pvz_plant_t.type");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, row) == 8, "pvz_plant_t.row");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, col) == 12, "pvz_plant_t.col");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, status_raw) == 16, "pvz_plant_t.status_raw");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, x) == 20, "pvz_plant_t.x");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, y) == 24, "pvz_plant_t.y");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, hp) == 28, "pvz_plant_t.hp");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, max_hp) == 32, "pvz_plant_t.max_hp");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, state_countdown) == 36, "pvz_plant_t.state_countdown");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, shoot_countdown) == 40, "pvz_plant_t.shoot_countdown");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, effect_countdown) == 44, "pvz_plant_t.effect_countdown");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, cob_state) == 48, "pvz_plant_t.cob_state");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, cob_recharge_countdown) == 52, "pvz_plant_t.cob_recharge_countdown");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, cob_charge_progress) == 56, "pvz_plant_t.cob_charge_progress");
PVZ_STATIC_ASSERT(offsetof(pvz_plant_t, flags) == 60, "pvz_plant_t.flags");

/* ---- pvz_zombie_t ---- */
/* Zombie, 80 bytes. Written iff: emulator !is_dead; game !is_disappeared && at_wave >= 0.
 * Dying zombies are written with DYING set. */
typedef struct pvz_zombie_t {
    /* @0 id: int32_t. valid: PVZ_VALID_Z_BASIC. */
    int32_t id;
    /* @4 type: int32_t. valid: PVZ_VALID_Z_BASIC.
     * zombie type code = the emulator enum value */
    int32_t type;
    /* @8 row: int32_t. valid: PVZ_VALID_Z_BASIC.
     * 0-based, row 0 top */
    int32_t row;
    /* @12 status_raw: int32_t. valid: PVZ_VALID_Z_STATUS.
     * raw status code, world-specific; encoder v1 must not read it */
    int32_t status_raw;
    /* @16 x: float, px, float32 in this world's own frame. valid: PVZ_VALID_Z_BASIC. */
    float x;
    /* @20 y: float, px, float32 in this world's own frame. valid: PVZ_VALID_Z_BASIC. */
    float y;
    /* @24 hp: int32_t. valid: PVZ_VALID_Z_HP. */
    int32_t hp;
    /* @28 max_hp: int32_t. valid: PVZ_VALID_Z_MAX_HP.
     * game: no row, unk */
    int32_t max_hp;
    /* @32 acc1_type: int32_t. valid: PVZ_VALID_ACC_TYPE.
     * accessory type code = the emulator enum value */
    int32_t acc1_type;
    /* @36 acc1_hp: int32_t. valid: PVZ_VALID_ACC_HP.
     * 0 when acc1_type is none
     * emulator: write hp = 0 when type is none, stale value survives slot reuse per E */
    int32_t acc1_hp;
    /* @40 acc1_max_hp: int32_t. valid: PVZ_VALID_ACC_TYPE.
     * 0 when acc1_type is none */
    int32_t acc1_max_hp;
    /* @44 acc2_type: int32_t. valid: PVZ_VALID_ACC_TYPE.
     * accessory type code = the emulator enum value */
    int32_t acc2_type;
    /* @48 acc2_hp: int32_t. valid: PVZ_VALID_ACC_HP.
     * 0 when acc2_type is none
     * emulator: write hp = 0 when type is none, stale value survives slot reuse per E */
    int32_t acc2_hp;
    /* @52 acc2_max_hp: int32_t. valid: PVZ_VALID_ACC_TYPE.
     * 0 when acc2_type is none */
    int32_t acc2_max_hp;
    /* @56 slow_countdown: int32_t, ticks. valid: PVZ_VALID_Z_DEBUFF. */
    int32_t slow_countdown;
    /* @60 freeze_countdown: int32_t, ticks. valid: PVZ_VALID_Z_DEBUFF. */
    int32_t freeze_countdown;
    /* @64 butter_countdown: int32_t, ticks. valid: PVZ_VALID_Z_DEBUFF. */
    int32_t butter_countdown;
    /* @68 spawn_wave: int32_t. valid: PVZ_VALID_Z_SPAWN_WAVE.
     * emulator: spawn_wave 0-based
     * game: at_wave, unk */
    int32_t spawn_wave;
    /* @72 flags: uint32_t.
     * PVZ_ZOMBIE_FLAG_*: bit0 EATING, bit1 IN_WATER, bit2 FLYING = balloon airborne only
     *   (emulator is_flying_or_falling(), emulator object/zombie.h:231-234), bit3 DYING =
     *   emulator has_death_status(): dying, dying_from_instant_kill, dying_from_lawnmower
     *   (emulator object/zombie.h:240-244; game state 1/2/3), bit4 HYPNO. Each bit has its
     *   own valid bit. */
    uint32_t flags;
    /* @76 _pad: uint32_t.
     * written as zero */
    uint32_t _pad;
} pvz_zombie_t;

PVZ_STATIC_ASSERT(sizeof(pvz_zombie_t) == 80, "pvz_zombie_t size");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, id) == 0, "pvz_zombie_t.id");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, type) == 4, "pvz_zombie_t.type");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, row) == 8, "pvz_zombie_t.row");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, status_raw) == 12, "pvz_zombie_t.status_raw");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, x) == 16, "pvz_zombie_t.x");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, y) == 20, "pvz_zombie_t.y");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, hp) == 24, "pvz_zombie_t.hp");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, max_hp) == 28, "pvz_zombie_t.max_hp");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, acc1_type) == 32, "pvz_zombie_t.acc1_type");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, acc1_hp) == 36, "pvz_zombie_t.acc1_hp");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, acc1_max_hp) == 40, "pvz_zombie_t.acc1_max_hp");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, acc2_type) == 44, "pvz_zombie_t.acc2_type");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, acc2_hp) == 48, "pvz_zombie_t.acc2_hp");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, acc2_max_hp) == 52, "pvz_zombie_t.acc2_max_hp");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, slow_countdown) == 56, "pvz_zombie_t.slow_countdown");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, freeze_countdown) == 60, "pvz_zombie_t.freeze_countdown");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, butter_countdown) == 64, "pvz_zombie_t.butter_countdown");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, spawn_wave) == 68, "pvz_zombie_t.spawn_wave");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, flags) == 72, "pvz_zombie_t.flags");
PVZ_STATIC_ASSERT(offsetof(pvz_zombie_t, _pad) == 76, "pvz_zombie_t._pad");

/* ---- pvz_griditem_t ---- */
/* Grid item, 16 bytes. */
typedef struct pvz_griditem_t {
    /* @0 type: int32_t. valid: PVZ_VALID_GRID.
     * grid item type code = the emulator enum value (grid item 1/2/3 match) */
    int32_t type;
    /* @4 row: int32_t. valid: PVZ_VALID_GRID.
     * 0-based, row 0 top */
    int32_t row;
    /* @8 col: int32_t. valid: PVZ_VALID_GRID.
     * 0-based */
    int32_t col;
    /* @12 countdown_raw: int32_t. valid: PVZ_VALID_GRID_COUNTDOWN.
     * meaning differs per world and type */
    int32_t countdown_raw;
} pvz_griditem_t;

PVZ_STATIC_ASSERT(sizeof(pvz_griditem_t) == 16, "pvz_griditem_t size");
PVZ_STATIC_ASSERT(offsetof(pvz_griditem_t, type) == 0, "pvz_griditem_t.type");
PVZ_STATIC_ASSERT(offsetof(pvz_griditem_t, row) == 4, "pvz_griditem_t.row");
PVZ_STATIC_ASSERT(offsetof(pvz_griditem_t, col) == 8, "pvz_griditem_t.col");
PVZ_STATIC_ASSERT(offsetof(pvz_griditem_t, countdown_raw) == 12, "pvz_griditem_t.countdown_raw");

/* ---- pvz_mower_t ---- */
/* Lawnmower, 16 bytes. Emulator: none modelled, n = 0, MOWERS bit off. Game: array +
 * is_dead have rows; row and x unk. Mowers never feed the policy (planner and game-only
 * shaping only). */
typedef struct pvz_mower_t {
    /* @0 row: int32_t. valid: PVZ_VALID_MOWERS.
     * 0-based, row 0 top */
    int32_t row;
    /* @4 x: float, px, float32 in this world's own frame. valid: PVZ_VALID_MOWERS. */
    float x;
    /* @8 state: int32_t. valid: PVZ_VALID_MOWERS.
     * PVZ_MOWER_STATE_*: 1 ready, 2 moving */
    int32_t state;
    /* @12 _pad: uint32_t.
     * written as zero */
    uint32_t _pad;
} pvz_mower_t;

PVZ_STATIC_ASSERT(sizeof(pvz_mower_t) == 16, "pvz_mower_t size");
PVZ_STATIC_ASSERT(offsetof(pvz_mower_t, row) == 0, "pvz_mower_t.row");
PVZ_STATIC_ASSERT(offsetof(pvz_mower_t, x) == 4, "pvz_mower_t.x");
PVZ_STATIC_ASSERT(offsetof(pvz_mower_t, state) == 8, "pvz_mower_t.state");
PVZ_STATIC_ASSERT(offsetof(pvz_mower_t, _pad) == 12, "pvz_mower_t._pad");

/* ---- pvz_state_t: the whole state, PVZ_STATE_SIZE bytes ---- */
typedef struct pvz_state_t {
    pvz_header_t hdr;
    pvz_card_t cards[PVZ_MAX_CARDS];
    pvz_plant_t plants[PVZ_MAX_PLANTS];
    pvz_zombie_t zombies[PVZ_MAX_ZOMBIES];
    pvz_griditem_t griditems[PVZ_MAX_GRIDITEMS];
    pvz_mower_t mowers[PVZ_MAX_MOWERS];
} pvz_state_t;

PVZ_STATIC_ASSERT(sizeof(pvz_state_t) == 59848, "pvz_state_t size");
PVZ_STATIC_ASSERT(sizeof(pvz_state_t) == PVZ_STATE_SIZE, "PVZ_STATE_SIZE");
PVZ_STATIC_ASSERT(offsetof(pvz_state_t, hdr) == 0, "pvz_state_t.hdr");
PVZ_STATIC_ASSERT(offsetof(pvz_state_t, cards) == 128, "pvz_state_t.cards");
PVZ_STATIC_ASSERT(offsetof(pvz_state_t, plants) == 328, "pvz_state_t.plants");
PVZ_STATIC_ASSERT(offsetof(pvz_state_t, zombies) == 16712, "pvz_state_t.zombies");
PVZ_STATIC_ASSERT(offsetof(pvz_state_t, griditems) == 57672, "pvz_state_t.griditems");
PVZ_STATIC_ASSERT(offsetof(pvz_state_t, mowers) == 59720, "pvz_state_t.mowers");
